# *1. 零训练样本分类*

In [1]:
from transformers import pipeline

In [2]:
classifier = pipeline("zero-shot-classification")

No model was supplied, defaulted to facebook/bart-large-mnli and revision d7645e1 (https://huggingface.co/facebook/bart-large-mnli).
Using a pipeline without specifying a model name and revision in production is not recommended.
/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/1.15k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

In [3]:
result = classifier(
    "This is a course about the Transformers library.",
    candidate_labels = ["education", "politics", "business", "comment"]
)

In [4]:
print(result)

{'sequence': 'This is a course about the Transformers library.', 'labels': ['education', 'comment', 'business', 'politics'], 'scores': [0.6840799450874329, 0.21549372375011444, 0.0737949013710022, 0.026631459593772888]}


# *2.情感分析*

In [5]:
from transformers import pipeline

In [6]:
classifier = pipeline("sentiment-analysis")

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.


config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

In [7]:
result = classifier("I've been waiting for HuggingFace course my whole life.")

In [8]:
print(result)

[{'label': 'POSITIVE', 'score': 0.985034167766571}]


In [9]:
results = classifier(
    ["I've been waiting for a HuggingFace course my whole life.", "I hate this so much!"]
)

In [10]:
print(results)

[{'label': 'POSITIVE', 'score': 0.9598049521446228}, {'label': 'NEGATIVE', 'score': 0.9994558691978455}]


# *3.文本生成*

In [11]:
from transformers import pipeline

In [12]:
generator = pipeline("text-generation", model="distilgpt2")

config.json:   0%|          | 0.00/762 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/353M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

In [13]:
results = generator("In this course, we will teach you how to")

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.


In [14]:
print(results)

[{'generated_text': 'In this course, we will teach you how to use a combination of the common sense and knowledge available as well as the well-developed approach that helps identify a problem in our system. To learn more, click here.\nFurther Resources'}]


In [15]:
results = generator(
    "In this course, we will teach you how to",
    num_return_sequences=2,
    truncation=True,
    max_length=30
)

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.


In [16]:
print(results)

[{'generated_text': 'In this course, we will teach you how to build scalable networks within this app that, without even using a built-in JavaScript module, will render'}, {'generated_text': 'In this course, we will teach you how to perform some interesting techniques in our language and how to use a method which you can use in your programming'}]


* 生成古诗词

In [17]:
generator = pipeline("text-generation", model="uer/gpt2-chinese-poem")

config.json:   0%|          | 0.00/577 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/425M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/271 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/115k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

In [18]:
results = generator(
    "[CLS] 万 叠 春 山 积 雨 晴，",
    max_length=40,
    num_return_sequences=2,
)

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


In [19]:
print(results)

[{'generated_text': '[CLS] 万 叠 春 山 积 雨 晴， 施 与 客 闲 。 夜 堂 闻 杜 鹃 泣 血 ， 朝 食 杏 花 疑 象 龙 。 一 物 不 同 之 字 法 ，'}, {'generated_text': '[CLS] 万 叠 春 山 积 雨 晴， 兹 千 顷 波 。 楼 上 多 好 风 终 日 ， 客 中 岁 晚 奈 情 何 。 见 远 峰 浓 又 淡 ，'}]


# *遮盖词填充*

In [20]:
from transformers import pipeline

In [21]:
unmasker = pipeline("fill-mask")

No model was supplied, defaulted to distilbert/distilroberta-base and revision fb53ab8 (https://huggingface.co/distilbert/distilroberta-base).
Using a pipeline without specifying a model name and revision in production is not recommended.


config.json:   0%|          | 0.00/480 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/331M [00:00<?, ?B/s]

Some weights of the model checkpoint at distilbert/distilroberta-base were not used when initializing RobertaForMaskedLM: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
- This IS expected if you are initializing RobertaForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

In [22]:
results = unmasker("This course will teach you all about <mask> models.", top_k=2)

In [23]:
print(results)

[{'score': 0.19198468327522278, 'token': 30412, 'token_str': ' mathematical', 'sequence': 'This course will teach you all about mathematical models.'}, {'score': 0.042092032730579376, 'token': 38163, 'token_str': ' computational', 'sequence': 'This course will teach you all about computational models.'}]


# *命名实体识别*

In [24]:
from transformers import pipeline

In [25]:
ner = pipeline("ner", grouped_entities=True)

No model was supplied, defaulted to dbmdz/bert-large-cased-finetuned-conll03-english and revision 4c53496 (https://huggingface.co/dbmdz/bert-large-cased-finetuned-conll03-english).
Using a pipeline without specifying a model name and revision in production is not recommended.


config.json:   0%|          | 0.00/998 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.33G [00:00<?, ?B/s]

Some weights of the model checkpoint at dbmdz/bert-large-cased-finetuned-conll03-english were not used when initializing BertForTokenClassification: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight']
- This IS expected if you are initializing BertForTokenClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForTokenClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


tokenizer_config.json:   0%|          | 0.00/60.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/transformers/pipelines/token_classification.py:170: UserWarning: `grouped_entities` is deprecated and will be removed in version v5.0.0, defaulted to `aggregation_strategy="simple"` instead.
  warnings.warn(


In [26]:
results = ner("My name is Sylvain and I work at Hugging Face in Brooklyn.")

In [27]:
print(results)

[{'entity_group': 'PER', 'score': 0.9981694, 'word': 'Sylvain', 'start': 11, 'end': 18}, {'entity_group': 'ORG', 'score': 0.9796019, 'word': 'Hugging Face', 'start': 33, 'end': 45}, {'entity_group': 'LOC', 'score': 0.9932106, 'word': 'Brooklyn', 'start': 49, 'end': 57}]


# *自动问答*

In [28]:
from transformers import pipeline

In [29]:
question_answerer = pipeline("question-answering")

No model was supplied, defaulted to distilbert/distilbert-base-cased-distilled-squad and revision 564e9b5 (https://huggingface.co/distilbert/distilbert-base-cased-distilled-squad).
Using a pipeline without specifying a model name and revision in production is not recommended.


config.json:   0%|          | 0.00/473 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/261M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/436k [00:00<?, ?B/s]

In [30]:
answer = question_answerer(
    question="Where do I work?",
    context="My name is Sylvain and I work at Hugging Face in Brooklyn"
)

In [31]:
print(answer)

{'score': 0.6949766278266907, 'start': 33, 'end': 45, 'answer': 'Hugging Face'}


# *自动摘要*

In [32]:
from transformers import pipeline

In [33]:
summarizer = pipeline("summarization")

No model was supplied, defaulted to sshleifer/distilbart-cnn-12-6 and revision a4f8f3e (https://huggingface.co/sshleifer/distilbart-cnn-12-6).
Using a pipeline without specifying a model name and revision in production is not recommended.


config.json:   0%|          | 0.00/1.80k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/1.22G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

In [34]:
results = summarizer(
    """
    America has changed dramatically during recent years. Not only has the number of
    graduates in traditional engineering disciplines such as mechanical, civil,
    electrical, chemical, and aeronautical engineering declined, but in most of
    the premier American universities engineering curricula now concentrate on
    and encourage largely the study of engineering science. As a result, there
    are declining offerings in engineering subjects dealing with infrastructure,
    the environment, and related issues, and greater concentration on high
    technology subjects, largely supporting increasingly complex scientific
    developments. While the latter is important, it should not be at the expense
    of more traditional engineering.

    Rapidly developing economies such as China and India, as well as other
    industrial countries in Europe and Asia, continue to encourage and advance
    the teaching of engineering. Both China and India, respectively, graduate
    six and eight times as many traditional engineers as does the United States.
    Other industrial countries at minimum maintain their output, while America
    suffers an increasingly serious decline in the number of engineering graduates
    and a lack of well-educated engineers.
    """
)

In [35]:
print(results)

[{'summary_text': ' America has changed dramatically during recent years . The number of engineering graduates in the U.S. has declined in traditional engineering disciplines such as mechanical, civil, electrical, chemical, and aeronautical engineering . Rapidly developing economies such as China and India, as well as other industrial countries in Europe and Asia, continue to encourage and advance engineering .'}]


# *使用分词器进行预处理*

In [36]:
from transformers import AutoTokenizer

In [37]:
checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

In [38]:
raw_inputs = [
    "I've been waiting for a HuggingFace course my whole life.",
    "I hate this so much!",
]

In [39]:
inputs = tokenizer(raw_inputs, padding=True, truncation=True, return_tensors="pt")

In [40]:
print(inputs)

{'input_ids': tensor([[  101,  1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662, 12172,
          2607,  2026,  2878,  2166,  1012,   102],
        [  101,  1045,  5223,  2023,  2061,  2172,   999,   102,     0,     0,
             0,     0,     0,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]])}


# *将预处理好的输入送入模型*

In [41]:
from transformers import AutoTokenizer, AutoModel

In [42]:
checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
# 分词器
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
# 模型
model = AutoModel.from_pretrained(checkpoint)

In [43]:
raw_inputs = [
    "I've been waiting for a HuggingFace course my whole life.",
    "I hate this so much!",
]

In [44]:
inputs = tokenizer(raw_inputs, padding=True, truncation=True, return_tensors="pt")

In [45]:
outputs = model(**inputs)

In [46]:
print(outputs.last_hidden_state.shape)

torch.Size([2, 16, 768])


## *对于情感分类的任务，最后需要使用的是一个文本分类的head，使用AtuoModelForSequenceClassification*

In [47]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification

In [48]:
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)

In [49]:
raw_inputs = [
    "I've been waiting for a HuggingFace course my whole life.",
    "I hate this so much!",
]

In [50]:
inputs = tokenizer(raw_inputs, padding=True, truncation=True, return_tensors="pt")
outputs = model(**inputs)

In [51]:
print(outputs.logits.shape)

torch.Size([2, 2])


In [52]:
# 所有 Transformers 模型都会输出 logits 值，因为训练时的损失函数通常会自动结合激活函数（例如 SoftMax）与实际的损失函数（例如交叉熵 cross entropy）。
print(outputs.logits)

tensor([[-1.5607,  1.6123],
        [ 4.1692, -3.3464]], grad_fn=<AddmmBackward0>)


In [53]:
# 将他们转换为概率值，还需要让他们经过一个softmax层
import torch

predictions = torch.nn.functional.softmax(outputs.logits, dim=-1)

print(predictions)

tensor([[4.0195e-02, 9.5980e-01],
        [9.9946e-01, 5.4418e-04]], grad_fn=<SoftmaxBackward0>)


In [54]:
print(model.config.id2label)

{0: 'NEGATIVE', 1: 'POSITIVE'}


# *分词器分词*

In [55]:
from transformers import AutoTokenizer

In [56]:
tokenizer = AutoTokenizer.from_pretrained("bert-base-cased")

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/436k [00:00<?, ?B/s]

In [57]:
sequence = "Using a Transformer network is simple"
tokens = tokenizer.tokenize(sequence)

In [59]:
print(tokens)
print(tokenizer(sequence))

['Using', 'a', 'Trans', '##former', 'network', 'is', 'simple']
{'input_ids': [101, 7993, 170, 13809, 23763, 2443, 1110, 3014, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1]}


In [61]:
ids = tokenizer.convert_tokens_to_ids(tokens)

In [64]:
print(ids)

# 采用encode 简化操作, 其中101和102分别是[CLS] [SEP]对应的token的IDs
print(tokenizer.encode(sequence))

[7993, 170, 13809, 23763, 2443, 1110, 3014]
[101, 7993, 170, 13809, 23763, 2443, 1110, 3014, 102]


In [65]:
# 采用decode将ids转为tokens并且将拆分的词进行了合并
decode_tokens = tokenizer.decode(ids)

print(decode_tokens)

token_ids = tokenizer.encode(sequence)

decode_tokens = tokenizer.decode(token_ids)

print(decode_tokens)

Using a Transformer network is simple
[CLS] Using a Transformer network is simple [SEP]


# *处理多行文本*

In [67]:
# 演示多行文本处理过程
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

model = AutoModelForSequenceClassification.from_pretrained(checkpoint)

sequence = "I've been waiting for a HuggingFace course my whole life."

tokens = tokenizer.tokenize(sequence)

ids = tokenizer.convert_tokens_to_ids(tokens)

print(ids)

input_ids = torch.tensor([ids])

print("Input IDs:\n", input_ids)

output = model(input_ids)

print("Logits:\n", output.logits)


[1045, 1005, 2310, 2042, 3403, 2005, 1037, 17662, 12172, 2607, 2026, 2878, 2166, 1012]
Input IDs:
 tensor([[ 1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662, 12172,  2607,
          2026,  2878,  2166,  1012]])
Logits:
 tensor([[-2.7276,  2.8789]], grad_fn=<AddmmBackward0>)


In [68]:
# 实际处理可以简化

tokenized_inputs = tokenizer(sequence, return_tensors="pt")

print("Inputs Keys:\n", tokenized_inputs.keys())

print("\nInput IDs:\n", tokenized_inputs["input_ids"])

print(tokenized_inputs)

output = model(**tokenized_inputs)

print(output.logits)

TypeError: PreTrainedTokenizerFast._batch_encode_plus() got an unexpected keyword argument 'return_toensors'